name: 'rajbos'
description: 'Write json from variable to file'
author: 'devops-actions'
inputs:  
  json:
    required: true
    description: 'The json you want to store'
  filename:
    required: true
    description: 'The filename you want to store the json in'
runs:
  using: 'node16'
  main: 'dist/main.js'
