name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  json:
    required: true
    description: 'The json you want to store'
  filename:
    required: true
    description: 'The filename you want to store the json in'
runs:
  using: 'node16'
  main: 'dist/main.js'
