name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci works properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - run: | 
          npm ci
          npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: store-json
        with:
          json: '{"foo": "test"}'
          filename: 'test.json'

      - shell: pwsh 
        name: test the file content       
        run: |
         $content = Get-Content -Path 'test.json'
         $test = $content | ConvertFrom-Json
         if ($test.foo -eq 'test') {
            Write-Host "File found correct"
         } 
         else {
            Write-Host "Found this json:"
            Write-Host $test | ConvertTo-Json
         }

      - run: |
          cat test.json
