name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      
permissions:
  contents: read

jobs:
  build: # make sure build/ci works properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      
      - uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - run: | 
          npm ci
          npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: ./
        id: store-json
        with:
          json: '{"foo": "test"}'
          filename: 'test.json'

      # todo: add test that checks with additional quotes in the value
      - shell: pwsh 
        name: test the file content       
        run: |
         $content = Get-Content -Path 'test.json'
         Write-Host "Found this content in the file:"
         Write-Host $content
         
         $test = $content | ConvertFrom-Json
         if ($test.foo -eq 'test') {
            Write-Host "File found correct"
         } 
         else {
            Write-Host "Found this json:"
            Write-Host $test | ConvertTo-Json
         }
